### ISSUE TITLE
Define `ShellError` exception.

### ISSUE THREAD

**Issue by damienstanton** [writecrow/ocr2text#3]
My environment is Python 3.8.5, macOS 11.1.

I'm taking a peek at this code to understand how to interface with tesseract, and the code fails linter checks:

```
Undefined variable 'exceptions'
```
referring to L66:
```python
raise exceptions.ShellError(
    " ".join(args),
    127,
    "",
    "",
)
```

Is the `ShellError` class defined in a package that was left out of the requirements?

**Comment by markfullmer** [comment]
Hi @damienstanton !

It looks like we do need to define the the `ShellError` class in this package. This logic referenced was derived from `textract` package, which defines that error here: https://github.com/deanmalmgren/textract/blob/9d739f807351fd9e430a193eca853f5f2171a82a/textract/exceptions.py#L63

I'll update the issue title to reflect the work needed.

**Comment by markfullmer** [comment]
A further bit of clarification, to answer your original question: the `exceptions` package itself is built into Python, and includes some built-in exceptions: https://docs.python.org/3/library/exceptions.html . However, `ShellException` is a custom exception, so that's why we will need to define it.

**Comment by damienstanton** [comment]
Right, I may have worded the question vaguely. I know how exception handling works in Python; I just wanted to clarify that `ShellError` was actually defined in an `exceptions` module that wasn't exported in a package listed in the requirements (which you've confirmed).

Thanks!

**Comment by AlainTiri** [comment]
I have a similar issue. It's work well on my pc (if i dont count out of memory or cpu temperatur), but I have this issue on my VPS.

`Traceback (most recent call last):
  File "ocr2text.py", line 56, in run
    pipe = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdftoppm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ocr2text.py", line 151, in <module>
    count = convert_recursive(source, destination, count)
  File "ocr2text.py", line 116, in convert_recursive
    count = convert(source_path, output_filename, count, pdfCounter)
  File "ocr2text.py", line 121, in convert
    text = extract_tesseract(sourcefile)
  File "ocr2text.py", line 86, in extract_tesseract
    stdout, _ = run(['pdftoppm', filename, base])
  File "ocr2text.py", line 64, in run
    raise exceptions.ShellError(
NameError: name 'exceptions' is not defined
`

'exceptions' is not recognized by PyCharm (underlined in red).

**Comment by juliosmelo** [comment]
Why not to return https://docs.python.org/3/library/exceptions.html#FileNotFoundError ?
